os:
- linux
services:
- docker
jdk:
- openjdk8
sudo: false
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
before_install:
- jdk_switcher use openjdk8
- java -version
install:
script:
- chmod +x build-services.sh
- ./build-services.sh
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false